# Generated by Django 5.0 on 2024-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(default="9876543210", max_length=20),
        ),
    ]
